# MACHINE-LEARNING-MODEL-IMPLEMENTATION
TASK 4 OF CODTECH IT
*COMPANY* : CODTECH IT  SOLUTIONS
*NAME*    : RATHINAVEL.B
*INTERN ID*: CT04WH125
*DOMAIN*: PYTHON PROGRAMMING
*DURATION*: 4 WEEKS
*MENTOR*: NEELA SANTHOSH
DESCRIPTION:
          FOR THIS TASK I USED PANDAS AND SKLEARN MODULE IN THIS CODING I USED PANDAS 
TO READ THE SPAM FILE HERE LATIN FOR NON ENGLISH LANGUAGE RENAME THE COLUMNS INTO LABEL
AND MESSAGE ENCODES LABELS HAM=0 AND SPAM=W USED TRAIN TEST SPLIT AND VALUES XTRAIN=MESSAGE
AND XTEST=LABEL AND YTRAIN =TEST20% AND YTEST=RANDOM STATE 42 
AND USES TFIDVECTORIZERS TO TRANFORM THE XTRAIN AND XTEST AND MULTINOMIALNB CHECK 
MESSAGE THAT  IT HAS SPAM WORDS WITH HIS LIBRARY AND  USES ACCURACY TO CALCULATE THE 
WHETHER THE MESSAGE IS SPAM OR HAM IF THE ACCURACY SCORE IS MORE THAN 50% THE 
MESSAGE IS SPAM ELSE ITS HAM
